config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  get '/' => 'pages#home'

  get '/users' => 'users#index'
  get '/signup' => 'users#new'
  post '/' => 'users#create'

  get '/profile' => 'users#show'
  get '/profile/edit' => 'users#edit', as: :profile_edit
  post '/profile' => 'users#update', as: :profile_update

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#delete'

  get '/admin' => 'admin/sessions#new'
  get '/admin/logout' => 'admin/sessions#delete'
  get 'admin/fountains' => 'admin/fountains#index'

  namespace :admin do
    resources :users, :sessions
  end
end

app/models/admin.rb
require 'bcrypt'

class Admin < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  def show_username
    [username].compact.join(" - ")
  end

end

app/models/fountain.rb
class Fountain < ActiveRecord::Base

  has_many :fountain_comments
  has_many :fountain_ratings
  has_many :fountain_checkins
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true

end

app/models/fountain_checkin.rb
class FountainCheckin < ActiveRecord::Base

    belongs_to :users
    belongs_to :fountains

end

app/models/fountain_comment.rb
class FountainComment < ActiveRecord::Base

  belongs_to :users
  belongs_to :fountains

end

app/models/fountain_rating.rb
class FountainRating < ActiveRecord::Base

    belongs_to :users
    belongs_to :fountains

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_secure_password

  has_many :fountain_comments
  has_many :fountain_ratings
  has_many :fountain_checkins

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def set_default_role
		unless self.role
			self.role = :user
		end
	end

  def show_username
    [username].compact.join(" - ").downcase
  end

  def show_name
    [name].compact.join(" - ").downcase
  end

  def show_email
    [email].compact.join(" - ").downcase
  end

  def show_home
    [home_location].compact.join(" - ").downcase
  end

end

app/models/waterbottle.rb
class Waterbottle < ActiveRecord::Base

  has_and_belongs_to_many :wbstores

  validates :name, presence: true, uniqueness: true
  
end

app/models/wbstore.rb
class Wbstore < ActiveRecord::Base

  has_many :waterbottles

  validates :name, presence: true
  validates :location, presence: true

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      WelcomeMailer.welcome_email(@user).deliver_now
      redirect_to '/admin/users'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to '/admin/users'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/admin/users'
  end

private

  def user_params
    params.require(:user).permit(:name, :username, :email, :home_location, :password, :password_confirmation)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authorized?

  def create
    @admin = Admin.new(admin_params)
    if @admin.valid?
      @admin.save
      session[:admin_id] = @admin.id
    else
      render :new
    end
  end

private
  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to root_path
    end
  end

  def admin_params
    params.require(:admin).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin

  def current_user
  	if @current_user.nil?
  		@current_user = User.find_by(id: session[:user_id])
  	else
  		@current_user
  	end
  end

  def current_admin
    if @current_admin.nil?
      @current_admin = Admin.find_by(id: session[:admin_id])
    else
      @current_admin
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "get excited! you've successfully signed in."
      redirect_to '#thedeal'
    else
      flash[:notice] = "oopsies! something went wrong. you sure that's your password?"
      redirect_to '/'
    end
  end

  def delete
    session.clear
    redirect_to '/'
  end



end

app/controllers/user_actions_controller.rb
class UserActionsController < ApplicationController

  def check_in

  end

  def comment

  end

  def rate

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @home_locations =   [
        ["",""],
        ["BCN", "BCN"],
        ["DC", "DC"]
      ]
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      # WelcomeMailer.welcome_email(@user).deliver_now
      flash[:alert] = "welcome to dame agua!"
      redirect_to '#thedeal'
    else
      flash[:notice] = "oops! it looks like there was an error. try again, homie!"
      redirect_to signup_path
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/'
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(user_params)
      redirect_to '/'
    else
      flash[:notice] = "oops! tt looks like there was an error. try again, homie!"
      redirect_to profile_path
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :username, :email, :home_location, :password, :password_confirmation)
  end
end

app/controllers/water_bottles_controller.rb
class WaterBottlesController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sesssions_helper.rb
module SesssionsHelper
end

app/helpers/user_actions_helper.rb
module UserActionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/water_bottles_helper.rb
module WaterBottlesHelper
end

app/views/admin/users/create.html.erb
<div id="user-created">
  user created!
</div>

app/views/admin/users/edit.html.erb
<div class="container" id="edit-form" style="margin-top: 0px;">
	<h1>Update User Profile</h1>
  <div class="divider-horizontal"></div>

	<%= form_for @user, url: edit_admin_user_path, method: 'get' do |f| %>

	  name: <br> <%= f.text_field :name, class: "text-center" %>
		<br>
	  email: <br> <%= f.text_field :email, class: "text-center" %>
		<br>
    username:  <br> <%= f.text_field :username, class: "text-center" %>
		<br>
	  password: <br> <%= f.password_field :password, class: "text-center" %>
		<br>
	  password confirmation: <br> <%= f.password_field :password_confirmation, class: "text-center" %>

		<div>
			<%= f.label :filepicker_url, "upload an avi" %> <br>
			<%= f.filepicker_field :filepicker_url %> <!-- User#filepicker_url is a regular string column -->
		</div>

    <div class="divider-horizontal"></div>
	  <%= f.submit "update user", class: "edit-user text-center" %>

	<% end %>

</div>

app/views/admin/users/home.html.erb
<div id="user-created">
  user created!
</div>

app/views/admin/users/index.html.erb
<div class="container" id="index">
		<% if flash[:notice] %>
			<div class="notice alert alert-success alert-dismissible" role="alert" style="margin-top: 10px"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
		<% end %>
		<div>

			<h1>Current Dame Agua Users</h1>
			<div id="divider-left"></div>
			<b><p> name | username | email </p></b>
			<div id="divider-left"></div>
			<% @users.each do  |user| %>
				<p id="user-list">
					<%= user.name %> |
					<%= user.username %> |
					<%= user.email %> |
					<%= button_to "delete user", admin_user_path(user), :method => "delete", :style => 'color: #b81f00', :class => 'btn-link', :id => 'create-user' %> |
					<%= link_to "edit user", edit_admin_user_path(user), :class => 'btn-link', :id => 'edit-user' %>
				</p>
			<% end %>
		</div>
		<div id="divider-left"></div>
		<%= link_to 'create new user', new_admin_user_path %>
</div>

app/views/admin/users/new.html.erb
<div class="container" id="signup-form" style="margin-top: 0px;">
	<h1>Create a New User</h1>
  <div class="divider-horizontal"></div>

	<%= form_for @user, url: '/admin/users', method: 'post' do |f| %>

	  name: <br> <%= f.text_field :name, class: "text-center" %>
	  email: <br> <%= f.text_field :email, class: "text-center" %>
    username:  <br> <%= f.text_field :username, class: "text-center" %>
	  password: <br> <%= f.password_field :password, class: "text-center" %>
	  password confirmation: <br> <%= f.password_field :password_confirmation, class: "text-center" %>

		<div>
			<%= f.label :filepicker_url, "upload an avi" %> <br>
			<%= f.filepicker_field :filepicker_url %> <!-- User#filepicker_url is a regular string column -->
		</div>

    <div class="divider-horizontal"></div>
	  <%= f.submit "dame agua", class: "signup-btn text-center" %>

	<% end %>

</div>

app/views/users/edit.html.erb
<div class="container" id="edit">
	<br>
	<% if flash[:notice] %>
		<div class="notice alert alert-danger alert-dismissible" role="alert"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
	<% end %>

	<div class="wrapper" id="edit-wrapper">
				<h1 id="edit-welcome" class="col-lg-6"> change what you want, <span style="color: #000085"><%= current_user.show_username %></span> </h1>

			<div class="col-md-6" id="edit-content">
				<%= form_for @user, url: profile_update_path, method: 'post' do |f| %>

				  <%= f.text_field :name, class: "text-center", placeholder: "name", placeholder: "name" %>
					<br>
				  <%= f.email_field :email, class: "text-center", placeholder: "email" %>
					<br>
			    <%= f.text_field :username, class: "text-center", placeholder: "username" %>
					<br>
				  <%= f.password_field :password, class: "text-center", placeholder: "password" %>
					<br>
				  <%= f.password_field :password_confirmation, class: "text-center", placeholder: "confirm password" %>
					<br>
				  <%= f.submit "update", class: "edit-btn text-center" %>

				<% end %>
			</div>
		</div>
</div>

app/views/users/index.html.erb
<div class = "container">
		<div class = "row">

			<h1>Current Dame Agua Users</h1>

			<% @users.each do  |user| %>
				<p> <%= user.username %> | <%= user.email %> </p>
			<% end %>

		</div>
</div>

app/views/users/new.html.erb
<div class="container" id="signup" style="margin-top: 0px;">
	<br>
	<% if flash[:notice] %>
		<div class="notice alert alert-danger alert-dismissible" role="alert"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
	<% end %>

	<div class="wrapper" id="signup-wrapper">
		<div class="col-md-6" id="signup-welcome">
			<h1><span style="color: #000085">join us</span>, you know you wanna</h1>
		</div>

		<div class="col-md-6" id="signup-content">
			<%= form_for @user, url: '/' do |f| %>

			  <%= f.text_field :name, class: "text-center", placeholder: "full name" %>
			  <br>
				<%= f.email_field :email, class: "text-center", placeholder: "email" %>
			  <br>
		    <%= f.text_field :username, class: "text-center", placeholder: "username" %>
			  <br>
				<%= f.password_field :password, class: "text-center", placeholder: "password" %>
			  <br>
				<%= f.password_field :password_confirmation, class: "text-center", placeholder: "confirm password" %>
				<br>
			  <%= f.submit "dame agua", class: "signup-btn text-center" %>

			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class = "container" id="profile">
	<div class="wrapper" id="profile-wrapper">

		<h1 id="profile-welcome" class="col-lg-6"> welcome back, <span style="color: #000085"><%= current_user.show_username %></span> </h1>

		<span class="col-lg-6" id="profile-content">
			<p> <b>username</b> <br><%= current_user.show_username %> </p>
			<p> <b>name</b> <br><%= current_user.show_name %> </p>
			<p> <b>email</b> <br><%= current_user.show_email %> </p>
			<button id="link"><%= link_to 'edit profile', profile_edit_path %></button>
		</span>
	</div>

</div>