config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  get '/' => 'pages#home'

  get '/users' => 'users#index'
  get '/signup' => 'users#new'
  post '/' => 'users#create'

  get '/profile' => 'users#show'
  get '/profile/edit' => 'users#edit', as: :profile_edit
  post '/profile' => 'users#update', as: :profile_update

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#delete'

  get '/admin' => 'admin/sessions#new'
  get '/admin/logout' => 'admin/sessions#delete'
  get 'admin/fountains' => 'admin/fountains#index'

  namespace :admin do
    resources :users, :sessions
  end
end

app/models/admin.rb
require 'bcrypt'

class Admin < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  def show_username
    [username].compact.join(" - ")
  end

end

app/models/fountain.rb
class Fountain < ActiveRecord::Base

  has_many :fountain_comments
  has_many :fountain_ratings
  has_many :fountain_checkins
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true

end

app/models/fountain_checkin.rb
class FountainCheckin < ActiveRecord::Base

    belongs_to :users
    belongs_to :fountains

end

app/models/fountain_comment.rb
class FountainComment < ActiveRecord::Base

  belongs_to :users
  belongs_to :fountains

end

app/models/fountain_rating.rb
class FountainRating < ActiveRecord::Base

    belongs_to :users
    belongs_to :fountains

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_secure_password

  has_many :fountain_comments
  has_many :fountain_ratings
  has_many :fountain_checkins

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def set_default_role
		unless self.role
			self.role = :user
		end
	end

  def show_username
    [username].compact.join(" - ").downcase
  end

  def show_name
    [name].compact.join(" - ").downcase
  end

  def show_email
    [email].compact.join(" - ").downcase
  end

  def show_home
    [home_location].compact.join(" - ").downcase
  end

end

app/models/waterbottle.rb
class Waterbottle < ActiveRecord::Base

  has_and_belongs_to_many :wbstores

  validates :name, presence: true, uniqueness: true
  
end

app/models/wbstore.rb
class Wbstore < ActiveRecord::Base

  has_many :waterbottles

  validates :name, presence: true
  validates :location, presence: true

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authorized?

  def create
    @admin = Admin.new(admin_params)
    if @admin.valid?
      @admin.save
      session[:admin_id] = @admin.id
    else
      render :new
    end
  end

private
  def authorized?
    unless current_user.has_role? :admin
      flash[:error] = "You are not authorized to view that page."
      redirect_to root_path
    end
  end

  def admin_params
    params.require(:admin).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "get excited! you've successfully signed in."
      redirect_to '#thedeal'
    else
      flash[:notice] = "oopsies! something went wrong. you sure that's your password?"
      redirect_to '/'
    end
  end

  def delete
    session.clear
    redirect_to '/'
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @home_locations =   [
        ["",""],
        ["BCN", "BCN"],
        ["DC", "DC"]
      ]
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      # WelcomeMailer.welcome_email(@user).deliver_now
      flash[:alert] = "welcome to dame agua!"
      redirect_to '#thedeal'
    else
      flash[:notice] = "oops! it looks like there was an error. try again, homie!"
      redirect_to signup_path
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/'
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(user_params)
      redirect_to '/'
    else
      flash[:notice] = "oops! tt looks like there was an error. try again, homie!"
      redirect_to profile_path
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :username, :email, :home_location, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sesssions_helper.rb
module SesssionsHelper
end

app/helpers/user_actions_helper.rb
module UserActionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/water_bottles_helper.rb
module WaterBottlesHelper
end

app/views/layouts/_adminfooter.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" id="adminfooter" style="min-height: 27px; color: white">
  <div class="container">
    you are logged in as an admin!
  </div>
</nav>

app/views/layouts/_adminnav.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="navbar navbar-default navbar-fixed-top" style="color: white">
<div id="adminnav">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="/admin" style="font-size: 20px; color: white">Dame Admin</a>
  </div>

  <div class="collapse navbar-collapse" id="adminnav" style="padding:0">
  <ul class="admin nav navbar-nav navbar-left" style="color: white">
    <li><a href="/admin/users">users<span class="sr-only">(current)</span></a></li>
    <li><a href="/admin/fountains">fountains</a></li>
  </ul>

  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <% if current_admin.present? %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-tint"></span></a>
          <ul class="dropdown-menu" id="logout-drop">
            <li>
              <%= link_to 'logout', admin_logout_path %>
            </li>
      <% end %>

</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" id="footer" style="min-height: 27px; color: white">
  <div class="container">
    <a href="http://www.thedopefactory.com" style="color: white">created by The Dope Factory.</a>
  </div>
</nav>

app/views/layouts/_gohomenav.html.erb
<div>
  <div class="navbar-fixed-bottom" id="dame-navbar">
    <ul class="nav navbar-nav nav-tabs list-unstyled navbar-right" role="tablist" style="border: none; color: #000085">
      <li><a href="/">back home</a></li>
    </ul>

    <ul class="user nav navbar-nav nav-tabs navbar-left" id="navbar" style="color:white">
      <li class="dropdown">
        <% if current_user.present? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-tint"</a>
            <ul class="dropdown-menu" id="logout-drop">
              <li style="padding: 0">
                <%= link_to 'profile', profile_path %>
                <%= link_to 'logout', logout_path %>
              </li>
        <% else %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">login</a>
          <ul class="dropdown-menu">
            <li>
              <%= form_tag "/login", class: "navbar-form navbar-left", role: "signin", id: "signin-form" do %>
                <div class="form-group">
                  <%= text_field_tag :username, nil, class: "form-control text-center", placeholder: "username" %>
                  <%= password_field_tag :password, nil, class: "form-control text-center", placeholder: "password", id: "signin-password" %>

                </div>
                <%= button_tag "get agua", class: "btn-submit btn btn-default btn-block", id: "btn-submit" %>
                <%= link_to "need help?", "/help", class: "btn-help btn btn-default btn-block", id: "btn-help" %>
              <% end %>
            </li>
          </ul>
          <li><a href="/signup">sign up</a></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="navbar navbar-default navbar-fixed-top" id="navbar" style="color: white">
<div id="navbar">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <!-- <a class="navbar-brand" href="/" style="font-size: 20px; color: white">Dame Agua</a> -->
  </div>



  <ul class="user nav navbar-nav" id="navbar" style="color:white">
    <li class="dropdown">
      <% if current_user.present? %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-tint"</a>
          <ul class="dropdown-menu" id="logout-drop">
            <li>
              <%= link_to 'profile', profile_path %>
              <%= link_to 'logout', logout_path %>
            </li>
      <% else %>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">login</a>
        <ul class="dropdown-menu">
          <li>
            <%= form_tag "/login", class: "navbar-form navbar-left", role: "signin", id: "signin-form" do -%>
              <div class="form-group">
                <%= text_field_tag :username, nil, class: "form-control text-center", placeholder: "username" %>
                <br>
                <%= password_field_tag :password, nil, class: "form-control text-center", placeholder: "password" %>
                <br>
              </div>
              <%= button_tag "get agua", class: "btn btn-default btn-block" %>
              <%= link_to "need help?", "/help", class: "btn btn-default btn-block" %>
            <% end %>
          </li>
        </ul>
        <li><a href="/signup">sign up</a></li>
    <% end %>
  </ul>
</div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dame Agua</title>


  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Josefin+Slab:300,400,600,700,300italic,400italic,600italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVbwB4MDPuOyIgFJtOxjM-4Xt5CLZXoyw"></script>


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

</head>

<body class="scroll" data-spy="scroll" data-target="#dame-navbar" style="position:relative; height: 100%; overflow-y: scroll;" class="<%= controller_name %> <%= action_name %>" style="background-color: #ededed; font-family: 'Quicksand', sans-serif !important;">

  <% if current_page?('/') %>
    <%= render partial: "layouts/navbar" %>
  <% else %>
    <%= render partial: "layouts/gohomenav" %>
  <% end %>

  <%= yield %>

  <!-- filepicker -->
  <%= filepicker_js_include_tag %>

</body>
</html>

app/views/pages/_dameagua.html.erb
<div class="container" id="find-agua" style="padding-top:0px">
  <div class="wrapper">
    <% if flash[:notice] %>
      <div class="notice alert alert-success alert-dismissible" role="alert"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    <% end %>
    <div class="container" id="aguaContainer">
      <br>
      <form class="row" id="searchForm">
        <input id="address" type="textbox" placeholder="enter address" class="row-lg-6">
        <input type="submit" value="search" class="searchsubmit row-lg-3">
        <input type="button" value="use current location" id="currentLocation" class="row-lg-3">
      </form>

      <div id="map-canvas" style="width: 1140px; height: 300px;"></div>

      <div class="btn-group-vertical method-buttons" role="group" aria-label="...">
        <button class="route-calculator"><img  data-meth="walk" src="/assets/walk.png"></button>
        <button class="route-calculator"><img  data-meth="bike" src="/assets/bike.png"></button>
        <button class="route-calculator" ><img data-meth="transit" src="/assets/transit.png"></button>
        <button class="route-calculator"><img  data-meth="drive" src="/assets/drive.png"></button>
      </div>
      <div id="directionsPanel">

      </div>
      <br>
      <!-- Button trigger modal -->
      <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="fountain-modal">add a fountain</button> -->
    </div>

    <!-- Modal -->
    <!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">know of a fountain that's not on our list? let us know.</h4>
          </div>
          <div class="modal-body">
            add fountain addition request form here
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="nevermind">nevermind</button>
            <button type="button" class="btn btn-primary" id="fountain-submit">submit</button>
          </div>
        </div>
      </div>
    </div> -->
  </div>
</div>

app/views/pages/_findbottles.html.erb
<div id="find-bottles" class="container">
  <div class="wrapper">

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="bottle-modal">add a bottle</button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">know of a bottle that's not on our list? let us know.</h4>
          </div>
          <div class="modal-body">
            add bottle addition request form here
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="nevermind">nevermind</button>
            <button type="button" class="btn btn-primary" id="fountain-submit">submit</button>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/_tapout.html.erb
<div id="tapout" class="container">
  <div class="wrapper">
    <div class="col-lg-6" id="tapout-content">
      <h2>get real, <span>your body needs water</span>.  here are some tips on how you can maximize your daily intake.</h2>
      <ul class="list-unstyled">
        <h3>make it visual</h3>
        <li>place rubber bands at the top of your water bottle and move one down for each bottle that you finish</li>
        <h3>make it a habit</h3>
        <li>drink a glass of water before every meal or right before you get into the shower </li>
        <h3>make it digital</h3>
        <li>set an hourly alarm or download an app to set daily goals</li>
      </ul>
    </div>
    <form class="col-lg-6" id="tapoutCalculator">
      <h1>tap out.</h1>
      <input type="text" placeholder="enter weight" id="weight" style="text-align:center">
      <br>
      <div class="buttons" id="tapout-buttons">
        <input type="button" value="kgs" id="kilo">
        <input type="button" value="lbs" id="pounds">
      </div>
      <br>
      <p id="result"></p>
      <p id="but"></p>
    </form>
  </div>
</div>

<div id="info">

</div>

app/views/pages/_thedeal.html.erb
<div class="container" id="the-deal" style="padding-top: 0">
  <div class="wrapper" id="deal-wrapper">

    <div id="deal-content">
      <h1><span>the deal.</span></h1>
      <div "divider-horizontal"></div><hr>

      <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/9624-200.png" id="icon1">
      <p>bottled water is expected to be the <span><b>number one packaged drink</b></span> come 2016</p>

      <br>
      <img src="http://baggotstreetwines.com/skin/frontend/default/vigoshop/images/countries/spain.png" id="icon2">
      <p>in 2014, <b>Spain</b> consumed <span><b>32.1 gallons</b></span> per capita</p>

      <br>
      <img src="https://cdn4.iconfinder.com/data/icons/icon-flat-icon-set/50/globe-2-512.png" id="icon1">
      <p>globally, around <span><b>200 billion</b></span> water bottles are consumed each year</p>

      <br>
      <img src="https://inkspand.s3.amazonaws.com/assets/Dollar-sign-icon-f54d1d5515903f1fc8709e4f31fc6658.png" id="icon2">
      <p>the global market for packaged water is valued at <span><b>$60 billion</b></span><p>
  </div>
</div>

app/views/pages/findbottles.html.erb
here are some water botles that you can buy

<div id="bottle-page">

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="bottle-modal">add a bottle</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">know of a bottle that's not on our list? let us know.</h4>
        </div>
        <div class="modal-body">
          add bottle addition request form here
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="nevermind">nevermind</button>
          <button type="button" class="btn btn-primary" id="fountain-submit">submit</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/help.html.erb
a form for users to contact the admin for help requests

app/views/pages/home.html.erb
<div id="whole-page">
<div id="my-carousel" class="carousel carousel-fade slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#my-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#my-carousel" data-slide-to="1"></li>
    <li data-target="#my-carousel" data-slide-to="2"></li>
    <!-- <li data-target="#my-carousel" data-slide-to="3"></li> -->
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" >
    <div class="item active" id="deal-item">
      <a href="#thedeal"><div class="overlay"></div>
        <img src="/assets/thedeal.jpg" style="height: 100%; width: 100%;" />
        <div class="carousel-caption" style="color: white;">
          <h1>the deal.</h1>
          <p>We're here to help you understand the environmental impact of global overconsumption, all while staying hydrated.</p>
        </div>
      </a>
    </div>

    <div class="item" id="agua-item">
      <div class="overlay"></div>
      <a href="#dameagua">
        <img src="/assets/findagua.jpg" style="height: 100%; width: 100%;" />
        <div class="carousel-caption" style="color: black;">
          <h1>find agua.</h1>
          <p>Thirsty, but on the run? Say no to plastic and let us help you find a free water source.</p>
        </div>
      </a>
    </div>

    <!-- <div class="item" id="bottles-item">
      <div class="overlay"></div>
      <a href="#findbottles">
        <img src="/assets/findbottles2.jpg" style="height: 100%; width: 100%;" />
        <div class="carousel-caption" style="color: black;">
          <h1>find bottles.</h1>
          <p>The bottle is as important as the agua. We have options for any budget.</p>
        </div>
      </a>
    </div> -->

    <div class="item" id="tapout-item">
      <div class="overlay"></div>
      <a href="#tapout">
        <img src="/assets/tapout.jpg" style="height: 100%; width: 100%;" id="tapout-img"/>
        <div class="carousel-caption" style="color: black;">
          <h1>tap out.</h1>
          <p>The earth needs water and so do you! Get some tips on how you can stay hydrated.</p>
        </div>
      </a>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">previous</span>
  </a>
  <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">next</span>
  </a>
</div>

  <div class="container-fluid content">
     <div id="thedeal">
        <%= render partial: "pages/thedeal" %>
     </div>
     <div id="dameagua">
        <%= render partial: "pages/dameagua" %>
     </div>
     <div id="tapout">
       <%= render partial: "pages/tapout" %>
     </div>
  </div>
</div>

app/views/pages/tapout.html.erb
<div id="tapout">
  <form id="tapoutCalculator">
    <input type="text" placeholder="enter weight" id="weight" style="text-align:center">
    <br>
    <div class="buttons">
      <input type="button" value="kgs/ml" id="kilo">
      <input type="button" value="lbs/oz" id="pounds">
    </div>
    <br>
    <p id="result"></p>
    <p id="divider"></p>
  </form>
</div>

<div id="info">

</div>